apiVersion: v1
kind: Service
metadata:
  name: ai-market-studio-ui
  labels:
    app: ai-market-studio-ui
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: ai-market-studio-ui
